# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Dalton' do

pod 'BFPaperButton'

end

target 'DaltonExtension' do

pod 'BFPaperButton'

end
